DROP TABLE call_directions IF EXISTS;
DROP TABLE calls IF EXISTS;
DROP TABLE operators IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE operators
(
  id                INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  cname             VARCHAR(255)            NOT NULL,
  fullname          VARCHAR(255)            NOT NULL

);
CREATE UNIQUE INDEX operators_unique_fullname_idx
  ON operators (cname, fullname);

CREATE TABLE calls
(
  id              INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  registered      TIMESTAMP DEFAULT now() NOT NULL,
  phone_num       VARCHAR(255) NOT NULL,
  customer        VARCHAR(255) NOT NULL,
  comment         VARCHAR(255) NOT NULL,
  operator_id     INTEGER      NOT NULL,
  FOREIGN KEY (operator_id) REFERENCES operators (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX calls_unique_operator_registered_idx
  ON calls (operator_id, registered);

CREATE TABLE call_directions
(
  call_id          INTEGER NOT NULL,
  direction        VARCHAR(255),
  CONSTRAINT call_directions_idx UNIQUE (call_id, direction),
  FOREIGN KEY (call_id) REFERENCES CALLS (id) ON DELETE CASCADE
);
